// Generated by W2C2BridgeGenerator
#include <stdarg.h>

struct _Point {
    float x;
    float y;
};

typedef struct _Point Point;

struct _Point MakePoint(float x, float y);

bool EqualPoints(struct _Point aPoint, struct _Point bPoint);

bool EqualPointValues(struct _Point *aPoint, struct _Point *bPoint);

