// Generated by W2C2BridgeGenerator
#include <stdarg.h>

struct _Point {
    float x;
    float y;
};

struct _Point MakePoint(float x, float y);

_Bool EqualPoints(struct _Point aPoint, struct _Point bPoint);

_Bool EqualPointValues(struct _Point *aPoint, struct _Point *bPoint);

